### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by German563**
Fullstack App
On local machine everything is working, if not check if baseUrl: "http://localhost:3000".
On https://herman.goldberg.crabdance.com/ work all elements exept searching, API is not allowing on my free plan to use CORS.

### CODE REVIEW

**Comment by German563** [comment]
Fullstack App
On local machine everything is working, if not check if baseUrl: "http://localhost:3000/".
On https://herman.goldberg.crabdance.com/ work all elements exept searching, API is not allowing on my free plan to use CORS.

**Comment by FiLLa-FaS** [comment]
Hi! Thank you for sending your project for review, I especially like your jsx markup and form validation implementing. Btw the project still has some troubles, I left several comments below, please fix them to get more points and pass this stage. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * It will be a pretty vague comment, but I'll try to describe here most common cases, so you can check your project more productive way. Unfortunately, the project has too many mismatches with the design page in all blocks and elements and on all screen resolutions. You need to check all sizes, text properties and spaces between blocks and elements for both pages and modals on 320px, 768px and 1440px screen resolutions and make sure that all looks similar with the design. Please make sure that the fonts are linked correctly, links don't have unnecessary underline and inputs/buttons/links don't have incorrect borders
    * When popup opens the rest of the page should have dark overlay according to the mockup
    * Content of the popup shouldn't extend outside the modal container on all screen resolutions
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page content shouldn't stretch on more than 1440px screen resolutions
    * The page scrolls horizontally on 1090px - 1125px screen resolutions
    * Note, that all page content should be centered horizontally on intermediate screen resolutions (side spaces should be equal to each others)
    * On some screen resolutions between 700px and 764px screen resolutions login/logout button are moved incorrectly https://pasteboard.co/UjrBUeCtXeEL.jpg
    * Text inside news card shouldn't overlap each other https://pasteboard.co/zezrRgvsG52R.png
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * All footer links should be opened in a new tab
- [ ]  Classes are named according to BEM specifications.
    * `main__section` class should be renamed, it should be a new block
    * You shouldn't use capital letters in class names
    * `card__line`, `login-form__bottomlink`, `SavedNews__Description` element class shouldn't be used outside its block class
    * You can't use elements of elements like `footer__wrapper__links` and `footer__wrapper__icons` classes
    * BEM modifier class `popup__container_tooltip` can't be used without base class  
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * home page has double `header` tag
    * `navigation` block should be a `nav` tag, not `section`
    * Please use correct semantic tags for `main__title`, `main__subtitle`, `NewsList__subtitle ` items
    * Please use correct semantic tag for all items inside news card
    * `Author` block should be a section, not `author__section`
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [ ] A `components` folder with JS and CSS files for the components.
      * css files should be placed inside `components` folder
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project contains eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Show more button should have correct default and hover states
    * Booking/trash buttons in news card should have hover and clicked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * Not all icons in `svg` format
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all `font-family` styles have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 39

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, you've done a great job. I marked more detailed comments about mismatches with design so you can fix them step by step, and more common comments about BEM implementing - they should be fixed throughout the project. Keep up the good work!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * header items should be aligned vertically on all screen resolutions 
    * Incorrect actual width of the search input with button 
    * Search button and input shouldn't have a black border
    * Incorrect distance between search form and the end of the `main` on 1440px, 768px, 320px
    * `newslist__button` looks incorrectly (please check the border and background color in default state)
    * Footer links shouldn't have underline
    * Header looks incorrectly on 768 viewport (please check text properties, location and spaces of all items inside the header)
    * Incorrect distance between header and `main__title` on 768, 320 viewports
    * Incorrect location of `main__title` on 768 viewport https://pasteboard.co/VrX20f2oaXqT.png
    * Incorrect text properties of the `newslist__subtitle` on 768 viewport
    * You need to check and fix all text properties and internal spaces and gaps between items in news card on 1440, 768 and 320 viewports
    * All content shouldn't extend outside its container https://pasteboard.co/o7dNMcbD7Jyt.png. Please check and fix all similar cases throughout the project
    * `about` section should have equal side spaces on 768 viewport
    * Incorrect text properties of the `about` section title on 768 viewport
    * Incorrect width of the footer section on 768 viewport
    * Mobile navigation menu looks incorrectly on 320 viewport (please check background color, text properties and location of all items and spaces between them)
    * About and footer sections overlap each other on 320 viewport and on 321px - 766 screen resolutions
    * Incorrect distance between footer and the end of the page on 320 viewport
    * Thin line between header and main shouldn't have side spaces on all screen resolutions (please check `saved-news` page)
    * You need to check and fix all spaces, sizes and text properties of all items inside `savednews__description` on 1440px, 768px and 320px screen resolutions
    *  You need to check and fix all spaces, sizes and text properties of all items inside modal window on 1440px, 768px and 320px screen resolutions
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page content shouldn't stretch on more than 1440px screen resolutions (it should keep its width)
    * `about` section looks broken on 767px
    * Modal windows should be centered vertically and horizontally on all screen resolutions
    * All pages content should be centered horizontally on all screen resolutions
    * login/logout button is moved incorrectly on 766px 
    * The page looks broken on 767 viewport
    * Text inside news card shouldn't overlap each other https://pasteboard.co/zezrRgvsG52R.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifier class should be used only with its base class - please fix all cases throughout the project
    * BEM element can't be used outside of its block - please fix all cases throughout the project
    * You can't use elements of elements like `block__element__element`, please fix all cases throughout the project
    * Please don't use capital letters in class names throughout the project
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Both pages has double `header` tag
    * navigation part has too many nested tags and double `nav` tags https://pasteboard.co/i4nquOWkSyvt.png
    * Author block should be a section, not `author__section`
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project contains eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Inactive tab in header shouldn't be white https://pasteboard.co/ERHLw2Qsrpnl.png
    * Show more button should have correct default and hover states
    * Booking/trash buttons in news card should have hover and clicked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `font-family` style in `main__button` doesn't have alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by FiLLa-FaS** [comment]
Hi! Thanks you for the corrections, there're still several comments below that you should fix to pass this stage. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `card__publishedat` looks incorrectly (please check the font and text properties for all screen resolutions)
    * Incorrect location of the right part of header section on 1440px (side spaces should be equal to each other)
    * Incorrect vertical spaces of `newslist__subtitle` on 1440px
    * Incorrect vertical margins of `card__source` (you need to reset them)
    * `about` section looks incorrectly on 1440px (please check the aligning of both columns)
    * Incorrect text properties of the `newslist__subtitle` on 768 viewport
    * Incorrect text properties of `card__title` on 768 viewport
    * Incorrect internal side spaces for all items inside news card on 768 and 320 viewports (note, that items should have side spaces, not only the left)
    * Incorrect left space of the footer copyright on 768 viewport
    * `about` section should have right space equal to the left space on 768 viewport
    * Incorrect distance between the start of the `about` section and content inside the section on 768 viewport
    * Incorrect text properties of `author__title` on 768 viewport
    * Incorrect distance between `header` and `main__title` on 320 viewport
    * Incorrect distance between search form and the end of the `main` on 320 viewport
    * Incorrect location of all items inside the footer except footer copyright on 320 viewport
    * Mobile navigation menu looks incorrectly on 320 viewport (please check background color, text properties and location of all items and spaces between them)
    * Incorrect distance between `savednews__subtitle` and the end of the section on 1440 viewport
    * You need to check and fix all sizes, spaces and text properties of the items inside `savednews__description` on 768 viewport
    * `header` and `savednews__description` looks incorrectly on 320 viewport (you should check all sizes, spaces and text properties)
    * Big space between the last card and footer section content on 320 viewport for `saved-news` page
    * Popup window looks incorrectly on all breakpoint screen resolutions (the block shoudn't be broken, you need to check all sizes and spaces of all items inside the window on all screen resolutions)
    * Incorrect height of the modal window on 320 viewport
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page content shouldn't stretch on more than 1440px screen resolutions (it should keep its width on bigger screen resolutions)
    * The page breaks on 767 viewport
    * All pages content should be centered horizontally on all screen resolutions (it means that all items should have similar side spaces - left space should be equal to the right space)
    * The modal window looks broken on 321px - 768px (and don't forget that the block should be centered horizontally)
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifier class should be used only with its base class - please fix all cases throughout the project
    * BEM element can't be used outside of its block - please fix all cases throughout the project
    * You can't use elements of elements like `block__element__element`, please fix all cases throughout the project
    * Please don't use capital letters in class names throughout the project
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Both pages has double `header` tag
    * navigation part has too many nested tags and double `nav` tags https://pasteboard.co/i4nquOWkSyvt.png
        * Author block should be a section, not `author__section`
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project contains eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Show more button should have correct default and hover states (please check the background color)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `font-family` style in `main__button` doesn't have alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by FiLLa-FaS** [comment]
Hi! Your project looks much better - great job! I added some screenshots to several issues below, so you can easily find and fix all the issues. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Incorrect font of the `card__publishedat` (should be `Source Sans Pro`)
    * Incorrect text properties of `newslist__subtitle` on 768 viewport
    * News card looks incorrectly on 768 viewport https://pasteboard.co/QCZ5blq4F17V.png (side spaces should be equal)
    * Mobile nav menu doesn't correspond the mockup https://pasteboard.co/WILx356KdoJa.png
    * Incorrect vertical spaces inside `saved-news` page on 1440, 768 viewports https://pasteboard.co/HQX5gPeSenRo.png
    * `header` and `saved-news__description` look incorrectly on 320 viewport https://pasteboard.co/eRyJ1XNmRpJL.png
    * Big space between the start of the footer and footer content on 320 viewport on `saved-news` page https://pasteboard.co/j53LcNGXTe8H.png
    * Popup window looks incorrectly on all screen resolutions (it has correct height on 1440px, but incorrect spaces between content elements. Note, that your popup window can have any amount of content and its height should be created dynamically depending of content that we put inside the popup window and gaps between them)
    * There shouldn't be two different icons when the popup is opened on 320 viewport https://pasteboard.co/J8MMTUtCyKJN.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page looks broken on 767 viewport https://pasteboard.co/a0njMGPD0iD7.png https://pasteboard.co/u4U8fKBk0LAb.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifier class should be used only with its base class (`block block_modifier` or `block__element block__element_modifier`), please fix all cases throughout the project
    * BEM element can't be used outside of its block (if you use `block__element` class, its parent should have `block` class), please fix all cases throughout the project
    * If you use `input-container` block class, then its children should have elements of `input-container` block classes
    * Please don't use capital letters in class names throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://pasteboard.co/ASeBI778fXkH.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

**Comment by FiLLa-FaS** [comment]
Hi! Your project is almost finished, several small issues below are left. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `header` and `saved-news__description` look incorrectly on 320 viewport https://pasteboard.co/eRyJ1XNmRpJL.png
    * Popup window looks incorrectly on 320 viewport (incorrect height of the popup, and bottom borders shouldn't be rounded)
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page looks broken on 767 viewport https://pasteboard.co/a0njMGPD0iD7.png 
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifier class should be used only with its base class (`block block_modifier` or `block__element block__element_modifier`), please fix all cases throughout the project
    * BEM element can't be used outside of its block (if you use `block__element` class, its parent should have `block` class), please fix all cases throughout the project
    * If you use `input-container` block class, then its children should have elements of `input-container` block classes
    * Please don't use capital letters in class names throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://pasteboard.co/ASeBI778fXkH.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

**Comment by FiLLa-FaS** [comment]
Hi! You need to fix at least one issue below to pass this stage, you're very close to the 80 points. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `saved-news__description` looks incorrectly on 320 viewport (please check all spaces and text properties of all items inside the container on 320 viewport)
    * Popup window looks incorrectly on 320 viewport (incorrect height of the popup, and bottom borders shouldn't be rounded)
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifier class should be used only with its base class (`block block_modifier` or `block__element block__element_modifier`), you can see the example on the screenshot https://pasteboard.co/BqcTWxkNxlvK.png, please fix all cases throughout the project 
    * BEM element can't be used outside of its block (if you use `block__element` class, its parent should have `block` class), you can see the example on the screenshot https://pasteboard.co/cr1ruOfijwot.png, please fix all cases throughout the project 
    * Note, that entity can't be BEM block and element of its block at the same time, you can see the example on the screenshot https://pasteboard.co/DmrEaK91PHkV.png. Please check and fix all similar cases throughout the project if you find them
    * Please don't use capital letters in class names throughout the project - you can separate different words using `-` symbol
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has some eslint warnings https://pasteboard.co/ASeBI778fXkH.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to accept this stage - congratulations! Good luck on the next stage 🚀

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Popup window shouldn't have empty space between the window and bottom screen edge on 320 viewport https://pasteboard.co/DOmcK7ly7vdE.png
        * `saved-news__description` looks incorrectly on 320 viewport (please check all spaces and text properties of all items inside the container on 320 viewport)
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use capital letters in class names throughout the project - you can separate different words using `-` symbol
    * modifier class should be used only with its base class (`block block_modifier` or `block__element block__element_modifier`), you can see the example on the screenshot https://pasteboard.co/KZ3RcM4Ozkp7.png, please fix all cases throughout the project
    * `footer_savednews` should be a key-value modifier instead of boolean one https://en.bem.info/methodology/quick-start/#key-value 
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 83

**Pull request merged**
